### ISSUE TITLE
Unlocking mutex without defer

### ISSUE THREAD

**Issue by kravcneger** [PacktPublishing/Hands-On-Software-Engineering-with-Golang#16]
https://github.com/PacktPublishing/Hands-On-Software-Engineering-with-Golang/blob/master/Chapter06/textindexer/store/memory/bleve.go#L77

Why do we unlock mutex without any guarantee?

**Comment by achilleasa** [comment]
Nice catch! There should be a `defer i.mu.Unlock()` call after line 66 to avoid holding the lock if the `return` statement on L73 is invoked.
